dist: trusty
sudo: required

compiler: gcc
language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - gcc-6
      - g++-6
      - cmake

before_install:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel -y

install:
  - npm install
  - npm install -g nightwatch

jobs:
  include:
    - stage: Nightwatch
    - script: nightwatch
    - stage: Nightwatch
    - script: ./node_modules/.bin/nightwatch 
